# Generated by Django 6.0.5 on 2026-05-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='google_event_id',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='CONFIRMADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='servico',
            name='duracao',
            field=models.IntegerField(default=120, help_text='Duração em minutos'),
        ),
    ]
